version: '3.8'
services:
  backend:
    image: balaji118/backend_image:v1
    build: .
    ports:
      - "8080:8080"
    networks:
      - recnetwork
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recycle_db
    ports:
      - "3306:3306"
    networks:
      - recnetwork
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
networks:
  recnetwork:
    driver: bridge